# Generated by Django 4.1.3 on 2022-12-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='made_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myapp.user'),
            preserve_default=False,
        ),
    ]
